# Generated by Django 4.0.1 on 2022-02-12 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=150, null=True, verbose_name='Bio')),
                ('profile_image', models.ImageField(null=True, upload_to='Profile-Pics', verbose_name='Bio')),
                ('country', models.CharField(choices=[], max_length=100, verbose_name='Country')),
                ('webiste_link', models.URLField(max_length=500, verbose_name='Webiste Link')),
                ('instagram_link', models.URLField(max_length=500, verbose_name='Instagram Link')),
                ('linkedin_link', models.URLField(max_length=500, verbose_name='LinkedIn Link')),
                ('twitter_link', models.URLField(max_length=500, verbose_name='Twitter Link')),
                ('email_confirmed', models.BooleanField(default=False, verbose_name='Is Confirmed?')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
